GET http://localhost:3000

### Valid battle

POST http://localhost:3000/pokemon/battles/simulate
Content-Type: application/json

{
  "teamA": {
    "name": "Kanto Starters",
    "pokemon": ["Bulbasaur", "Squirtle"]
  },
  "teamB": {
    "name": "Fire Line",
    "pokemon": ["004", "Charmeleon"]
  }
}

### Uneven battle

POST http://localhost:3000/pokemon/battles/simulate
Content-Type: application/json

{
  "teamA": {
    "name": "Many Weak Picks",
    "pokemon": ["Caterpie", "Weedle", "Pidgey", "Rattata", "Zubat"]
  },
  "teamB": {
    "name": "Single Heavy Hitter",
    "pokemon": ["Dragonite"]
  }
}

### Not found

POST http://localhost:3000/pokemon/battles/simulate
Content-Type: application/json

{
  "teamA": {
    "name": "Kanto Starters",
    "pokemon": ["Bulbasaur", "Squirtle", "Susu"]
  },
  "teamB": {
    "name": "Fire Line",
    "pokemon": ["004", "Charmeleon", "1200"]
  }
}

### Invalid

POST http://localhost:3000/pokemon/battles/simulate
Content-Type: application/json

{
  "teamA": {
    "name": "Kanto Starters",
    "pokemon": ["Bulbasaur", "Squirtle", "Susu", 2348]
  },
  "teamB": {
    "name": "Fire Line",
    "pokemon": ["004", "Charmeleon", "1200", false]
  }
}

### Invalid 2

POST http://localhost:3000/pokemon/battles/simulate
Content-Type: application/json

{
  "teamA": {
    "name": "Kanto Starters",
    "pokemon": ["Bulbasaur", "Squirtle", "Susu", 2348]
  },
  "teamB": {
    "name": "Fire Line",
    "pokemon": ["004", "Charmeleon", "1200", ""]
  }
}

### Invalid 3

POST http://localhost:3000/pokemon/battles/simulate
Content-Type: application/json

{
  "teamA": {
    "name": "Kanto Starters",
    "pokemon": ["Bulbasaur", "Squirtle", "Susu", 2348]
  },
  "teamB": {
    "name": "Fire Line",
    "pokemon": ["004", "Charmeleon", "1200", " sdf dfdsdfsd sdfsdf asds df sadf sdfsd sdfsdfs dfs dfs df"]
  }
}
