services:
  api:
    build: .
    image: pokemon-game-api
    container_name: pokemon-game
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: pokemon-game-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  seed:
    build: .
    image: pokemon-game-api
    env_file:
      - .env.production
    depends_on:
      - mongo
    volumes:
      - ./data:/app/data:ro
    command: ["node", "dist/cli/seed/seed-pokemon.js"]
    profiles:
      - seed

volumes:
  mongo_data: